User feature
mostafaism1/online-store-1 pull request #2
Opened 2021-01-15 14:58 UTC by mostafaism1

2021-01-15 15:18 UTC, Jezorko requested changes

2021-01-15 15:18 UTC, Jezorko commented on src/main/java/com/example/onlinestore/user/User.java
> +package com.example.onlinestore.user;
[nitpick] domains usually use plural form:
```suggestion
package com.example.onlinestore.users;
```

2021-01-15 15:18 UTC, Jezorko commented on src/main/java/com/example/onlinestore/user/User.java
> +    @Column(name = "user_name")
No need, Hibernate will transform all camelCase names to snake_case automatically (:
```suggestion
```

2021-01-15 15:18 UTC, Jezorko commented on src/main/java/com/example/onlinestore/user/User.java
> +    @Email
Validation should be on user creation request and not DB entity. Not sure if it even works here?

```suggestion
```

2021-01-15 15:18 UTC, Jezorko commented on src/main/java/com/example/onlinestore/user/User.java
> +        return Arrays.asList(new SimpleGrantedAuthority("USER"));
[IDE] Please pay more attention to [your IDE warnings](https://www.jetbrains.com/help/idea/code-inspection.html). This code shows:

> Call to 'asList()' with only one argument 

```suggestion
        return Collections.singletonList(new SimpleGrantedAuthority("USER"));
```

2021-01-15 15:18 UTC, Jezorko commented on src/main/java/com/example/onlinestore/user/UserRepository.java
> +        User findByUserName(String userName);
You can format file automatically with `Ctrl`+`Alt`+`L`
```suggestion
    User findByUserName(String userName);
```

2021-01-15 15:18 UTC, Jezorko commented on src/main/java/com/example/onlinestore/user/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
Repositories should not be `public`:
```suggestion
interface UserRepository extends JpaRepository<User, Long> {    
```

2021-01-15 15:18 UTC, Jezorko commented on src/main/java/com/example/onlinestore/user/UserRepositoryUserDetailsService.java
> +    private UserRepository userRepo;
```suggestion
    private final UserRepository userRepo;
```

2021-01-15 15:18 UTC, Jezorko commented on src/main/java/com/example/onlinestore/user/UserRepositoryUserDetailsService.java
> +public class UserRepositoryUserDetailsService implements UserDetailsService {
```suggestion
class UserRepositoryUserDetailsService implements UserDetailsService {
```

2021-01-15 15:18 UTC, Jezorko commented on src/main/java/com/example/onlinestore/user/UserRepositoryUserDetailsService.java
> +    }
You can replace this constructor with `@RequiredArgsConstructor` (Lombok-generated constructors have annotations necessary for autowiring on them)

2021-01-15 15:18 UTC, Jezorko commented on src/main/resources/SecurityConfig.java
> +public class SecurityConfig extends WebSecurityConfigurerAdapter {
```suggestion
class SecurityConfig extends WebSecurityConfigurerAdapter {
```

2021-01-15 15:18 UTC, Jezorko commented on src/main/resources/SecurityConfig.java
> +    UserDetailsService userDetailsSerive;
Prefer constructor over field injection:
```suggestion
@RequiredArgsConstructor
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    private final UserDetailsService userDetailsSerive;
```

2021-01-15 15:18 UTC, Jezorko commented on src/main/resources/SecurityConfig.java
> +public class SecurityConfig extends WebSecurityConfigurerAdapter {
Why is this class in `resources` and not `src/java`? :thinking:

2021-01-15 15:18 UTC, Jezorko commented on src/main/resources/SecurityConfig.java
> +    public PasswordEncoderr encoder() {
```suggestion
    PasswordEncoderr encoder() { 
```

2021-01-15 15:18 UTC, Jezorko commented on src/main/resources/data.sql
> +('username1', 'pass1', 'name1', 'email1@email.com'),
Why not make `email` your `username`?

2021-01-15 15:18 UTC, Jezorko commented on src/main/resources/schem.sql
> +);
No need to create a schema file, Hibernate is smart enough to build the database up from entity classes. Also `schema` instead of `schem` (;

2021-01-15 15:18 UTC, Jezorko commented on src/main/resources/schema-diagram.txt
> +@startuml
Nice!

2021-01-15 15:51 UTC, mostafaism1 commented on src/main/resources/data.sql
> +('username1', 'pass1', 'name1', 'email1@email.com'),
implementing the UserDetails interface requires a getUsername method,
but I suppose I could just return the email as the username regardless.

2021-01-15 16:00 UTC, mostafaism1 commented on src/main/resources/schema-diagram.txt
> +@startuml
schema as code is really neat

2021-01-15 16:01 UTC, mostafaism1 commented on src/main/resources/schem.sql
> +);
alright, that's considered code first, right?
ah that's a typo

2021-01-15 16:03 UTC, mostafaism1 commented on src/main/resources/SecurityConfig.java
> +    public PasswordEncoderr encoder() {
that makes it package private by default, correct?

2021-01-15 16:05 UTC, mostafaism1 commented on src/main/java/com/example/onlinestore/user/User.java
> +package com.example.onlinestore.user;
got it.

2021-01-15 16:07 UTC, mostafaism1 commented on src/main/java/com/example/onlinestore/user/User.java
> +    @Column(name = "user_name")
that's neat, 
what if I instead had it in camelCase in the db, would I need to specify the column name?

2021-01-15 16:13 UTC, mostafaism1 commented on src/main/java/com/example/onlinestore/user/User.java
> +    @Email
I think it's more robust to have the validations at the domain level,
this way the validations are declarative,
errors can then propagate up to the controller or view.

2021-01-15 16:16 UTC, Jezorko commented on src/main/java/com/example/onlinestore/user/User.java
> +    @Column(name = "user_name")
Yes, if you wanted to have it as `camelCase` you'd need to specify here or configure the naming strategy: https://www.baeldung.com/hibernate-naming-strategy

2021-01-15 16:16 UTC, mostafaism1 commented on src/main/resources/SecurityConfig.java
> +public class SecurityConfig extends WebSecurityConfigurerAdapter {
my bad,
do I create a configuration directory inside src/java?

2021-01-15 16:17 UTC, Jezorko commented on src/main/java/com/example/onlinestore/user/User.java
> +    @Email
Fair enough but double check if it actually works, I'm not 100% sure

2021-01-15 16:18 UTC, mostafaism1 commented on src/main/java/com/example/onlinestore/user/UserRepository.java
> +        User findByUserName(String userName);
noted :D

2021-01-15 16:19 UTC, Jezorko commented on src/main/resources/SecurityConfig.java
> +    public PasswordEncoderr encoder() {
Only the method, yes. You can still inject `PasswordEncoderr` anywhere (also just noticed it should be one `r` at the end :sweat_smile:)

2021-01-15 16:19 UTC, Jezorko commented on src/main/resources/data.sql
> +('username1', 'pass1', 'name1', 'email1@email.com'),
Yup, then you also have a guarantee the email will be unique (and you can use it as ID) (;

2021-01-15 16:19 UTC, mostafaism1 commented on src/main/java/com/example/onlinestore/user/User.java
> +        return Arrays.asList(new SimpleGrantedAuthority("USER"));
will do :+1:

2021-01-15 16:20 UTC, Jezorko commented on src/main/resources/schem.sql
> +);
Pretty much yep!

2021-01-15 16:47 UTC, mostafaism1 commented on src/main/java/com/example/onlinestore/user/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
what if another package requires access?

2021-01-15 16:49 UTC, mostafaism1 commented on src/main/java/com/example/onlinestore/user/UserRepositoryUserDetailsService.java
> +    private UserRepository userRepo;
that makes sense,
should all dependencies be declared final?

2021-01-15 17:13 UTC, mostafaism1 commented on src/main/resources/SecurityConfig.java
> +public class SecurityConfig extends WebSecurityConfigurerAdapter {
done

2021-01-15 17:14 UTC, mostafaism1 commented on src/main/java/com/example/onlinestore/user/UserRepositoryUserDetailsService.java
> +    }
good suggestion, it would make the code clearer.

2021-01-16 12:55 UTC, Jezorko commented on src/main/resources/data.sql
> +('email2@email.com', 'pass2', 'name2');
Passwords are hashed during login, plaintext passwords will not be recognized:

```suggestion
('email1@email.com', '$2a$10$H27RX92/KnQywQOF7l/VCeIa2g77.4pIbldPwrr.Ar8Qw.JXPGokC', 'name1'),
('email2@email.com', '$2a$10$Lhdy33w8QaV/bJutecweGOrSOAyjUOxz6IAexCtOyRl9ghfsXeWRW', 'name2');
```

> 2021-01-16 13:49:30.670  WARN 7006 --- [nio-8080-exec-6] o.s.s.c.bcrypt.BCryptPasswordEncoder     : Encoded password does not look like BCrypt

2021-01-16 15:43 UTC, mostafaism1 commented on src/main/resources/data.sql
> +('email2@email.com', 'pass2', 'name2');
you're a life saver!

2021-01-16 17:16 UTC, merged